// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (name, email, password_hash, phone_number, country, username, role, email_verified)
VALUES ($1, $2, $3, $4, $5, $6, 'admin', TRUE)
ON CONFLICT (email) WHERE deleted_at IS NULL DO UPDATE
SET role = 'admin', email_verified = TRUE
RETURNING id, name, email, password_hash, phone_number, country, username, role, email_verified, created_at, updated_at, deleted_at
`

type CreateAdminUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	Country      string      `json:"country"`
	Username     string      `json:"username"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.PhoneNumber,
		arg.Country,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.Country,
		&i.Username,
		&i.Role,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
