// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Category struct {
	ID        int64            `json:"id"`
	Slug      string           `json:"slug"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type OtpCode struct {
	Email      string             `json:"email"`
	HashedCode string             `json:"hashed_code"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
}

type Product struct {
	ID                    int64            `json:"id"`
	Name                  string           `json:"name"`
	PriceInCents          int32            `json:"price_in_cents"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	Slug                  pgtype.Text      `json:"slug"`
	ShortName             pgtype.Text      `json:"short_name"`
	CategoryID            pgtype.Int8      `json:"category_id"`
	IsNew                 bool             `json:"is_new"`
	Description           pgtype.Text      `json:"description"`
	Features              pgtype.Text      `json:"features"`
	BoxIncludes           []byte           `json:"box_includes"`
	Gallery               []byte           `json:"gallery"`
	CategoryImage         pgtype.Text      `json:"category_image"`
	RecommendedProductIds []int64          `json:"recommended_product_ids"`
}

type User struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	PhoneNumber   pgtype.Text        `json:"phone_number"`
	Country       string             `json:"country"`
	Username      string             `json:"username"`
	Role          UserRole           `json:"role"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
