// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOTP = `-- name: DeleteOTP :exec
DELETE FROM otp_codes
WHERE email = $1
`

func (q *Queries) DeleteOTP(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOTP, email)
	return err
}

const getOTP = `-- name: GetOTP :one
SELECT hashed_code, expires_at, attempts
FROM otp_codes
WHERE email = $1
`

type GetOTPRow struct {
	HashedCode string             `json:"hashed_code"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
}

func (q *Queries) GetOTP(ctx context.Context, email string) (GetOTPRow, error) {
	row := q.db.QueryRow(ctx, getOTP, email)
	var i GetOTPRow
	err := row.Scan(&i.HashedCode, &i.ExpiresAt, &i.Attempts)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes
SET attempts = attempts + 1
WHERE email = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, email)
	return err
}

const saveOTP = `-- name: SaveOTP :exec
INSERT INTO otp_codes (email, hashed_code, expires_at, attempts)
VALUES ($1, $2, $3, 0)
ON CONFLICT (email) DO UPDATE
SET hashed_code = EXCLUDED.hashed_code,
    expires_at = EXCLUDED.expires_at,
    attempts = 0
`

type SaveOTPParams struct {
	Email      string             `json:"email"`
	HashedCode string             `json:"hashed_code"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SaveOTP(ctx context.Context, arg SaveOTPParams) error {
	_, err := q.db.Exec(ctx, saveOTP, arg.Email, arg.HashedCode, arg.ExpiresAt)
	return err
}
