// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    price_in_cents,
    slug,
    short_name,
    category_id,
    is_new,
    description,
    features,
    box_includes,
    gallery,
    category_image,
    recommended_product_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids
`

type CreateProductParams struct {
	Name                  string      `json:"name"`
	PriceInCents          int32       `json:"price_in_cents"`
	Slug                  pgtype.Text `json:"slug"`
	ShortName             pgtype.Text `json:"short_name"`
	CategoryID            pgtype.Int8 `json:"category_id"`
	IsNew                 bool        `json:"is_new"`
	Description           pgtype.Text `json:"description"`
	Features              pgtype.Text `json:"features"`
	BoxIncludes           []byte      `json:"box_includes"`
	Gallery               []byte      `json:"gallery"`
	CategoryImage         pgtype.Text `json:"category_image"`
	RecommendedProductIds []int64     `json:"recommended_product_ids"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.PriceInCents,
		arg.Slug,
		arg.ShortName,
		arg.CategoryID,
		arg.IsNew,
		arg.Description,
		arg.Features,
		arg.BoxIncludes,
		arg.Gallery,
		arg.CategoryImage,
		arg.RecommendedProductIds,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.Slug,
		&i.ShortName,
		&i.CategoryID,
		&i.IsNew,
		&i.Description,
		&i.Features,
		&i.BoxIncludes,
		&i.Gallery,
		&i.CategoryImage,
		&i.RecommendedProductIds,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.Slug,
		&i.ShortName,
		&i.CategoryID,
		&i.IsNew,
		&i.Description,
		&i.Features,
		&i.BoxIncludes,
		&i.Gallery,
		&i.CategoryImage,
		&i.RecommendedProductIds,
	)
	return i, err
}

const getFeaturedProduct = `-- name: GetFeaturedProduct :one
SELECT id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids FROM products
WHERE is_new = TRUE
ORDER BY id
LIMIT 1
`

func (q *Queries) GetFeaturedProduct(ctx context.Context) (Product, error) {
	row := q.db.QueryRow(ctx, getFeaturedProduct)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.Slug,
		&i.ShortName,
		&i.CategoryID,
		&i.IsNew,
		&i.Description,
		&i.Features,
		&i.BoxIncludes,
		&i.Gallery,
		&i.CategoryImage,
		&i.RecommendedProductIds,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.Slug,
		&i.ShortName,
		&i.CategoryID,
		&i.IsNew,
		&i.Description,
		&i.Features,
		&i.BoxIncludes,
		&i.Gallery,
		&i.CategoryImage,
		&i.RecommendedProductIds,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids FROM products WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug pgtype.Text) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.Slug,
		&i.ShortName,
		&i.CategoryID,
		&i.IsNew,
		&i.Description,
		&i.Features,
		&i.BoxIncludes,
		&i.Gallery,
		&i.CategoryImage,
		&i.RecommendedProductIds,
	)
	return i, err
}

const getRecommendedProducts = `-- name: GetRecommendedProducts :many
SELECT p.id, p.name, p.price_in_cents, p.created_at, p.slug, p.short_name, p.category_id, p.is_new, p.description, p.features, p.box_includes, p.gallery, p.category_image, p.recommended_product_ids FROM products p
WHERE p.id = ANY (
    SELECT unnest(rp.recommended_product_ids) FROM products rp WHERE rp.id = $1
)
`

func (q *Queries) GetRecommendedProducts(ctx context.Context, id int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, getRecommendedProducts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.CreatedAt,
			&i.Slug,
			&i.ShortName,
			&i.CategoryID,
			&i.IsNew,
			&i.Description,
			&i.Features,
			&i.BoxIncludes,
			&i.Gallery,
			&i.CategoryImage,
			&i.RecommendedProductIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids FROM products
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.CreatedAt,
			&i.Slug,
			&i.ShortName,
			&i.CategoryID,
			&i.IsNew,
			&i.Description,
			&i.Features,
			&i.BoxIncludes,
			&i.Gallery,
			&i.CategoryImage,
			&i.RecommendedProductIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT p.id, p.name, p.price_in_cents, p.created_at, p.slug, p.short_name, p.category_id, p.is_new, p.description, p.features, p.box_includes, p.gallery, p.category_image, p.recommended_product_ids
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE c.slug = $1
ORDER BY p.is_new DESC, p.id
`

func (q *Queries) ListProductsByCategory(ctx context.Context, slug string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.CreatedAt,
			&i.Slug,
			&i.ShortName,
			&i.CategoryID,
			&i.IsNew,
			&i.Description,
			&i.Features,
			&i.BoxIncludes,
			&i.Gallery,
			&i.CategoryImage,
			&i.RecommendedProductIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    price_in_cents = $3,
    slug = $4,
    short_name = $5,
    category_id = $6,
    is_new = $7,
    description = $8,
    features = $9,
    box_includes = $10,
    gallery = $11,
    category_image = $12,
    recommended_product_ids = $13
WHERE id = $1
RETURNING id, name, price_in_cents, created_at, slug, short_name, category_id, is_new, description, features, box_includes, gallery, category_image, recommended_product_ids
`

type UpdateProductParams struct {
	ID                    int64       `json:"id"`
	Name                  string      `json:"name"`
	PriceInCents          int32       `json:"price_in_cents"`
	Slug                  pgtype.Text `json:"slug"`
	ShortName             pgtype.Text `json:"short_name"`
	CategoryID            pgtype.Int8 `json:"category_id"`
	IsNew                 bool        `json:"is_new"`
	Description           pgtype.Text `json:"description"`
	Features              pgtype.Text `json:"features"`
	BoxIncludes           []byte      `json:"box_includes"`
	Gallery               []byte      `json:"gallery"`
	CategoryImage         pgtype.Text `json:"category_image"`
	RecommendedProductIds []int64     `json:"recommended_product_ids"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.PriceInCents,
		arg.Slug,
		arg.ShortName,
		arg.CategoryID,
		arg.IsNew,
		arg.Description,
		arg.Features,
		arg.BoxIncludes,
		arg.Gallery,
		arg.CategoryImage,
		arg.RecommendedProductIds,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.Slug,
		&i.ShortName,
		&i.CategoryID,
		&i.IsNew,
		&i.Description,
		&i.Features,
		&i.BoxIncludes,
		&i.Gallery,
		&i.CategoryImage,
		&i.RecommendedProductIds,
	)
	return i, err
}
