package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"encoding/json"
	"fmt"
	"github/M-b-a-s/e-comm/graph/model"
	repo "github/M-b-a-s/e-comm/internal/adapters/postgresql/sqlc"
	"github/M-b-a-s/e-comm/internal/auth"
	"strconv"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	boxIncludes, err := json.Marshal(input.BoxIncludes)
	if err != nil {
		return nil, fmt.Errorf("marshal box includes: %w", err)
	}

	product, err := r.Queries.CreateProduct(ctx, repo.CreateProductParams{
		Name:                  input.Name,
		PriceInCents:          input.PriceInCents,
		Slug:                  pgtype.Text{String: input.Slug, Valid: true},
		ShortName:             pgtype.Text{String: input.ShortName, Valid: true},
		CategoryID:            pgtype.Int8{Int64: int64(input.CategoryID), Valid: true},
		IsNew:                 input.IsNew,
		Description:           pgtype.Text{String: input.Description, Valid: true},
		Features:              pgtype.Text{String: input.Features, Valid: true},
		BoxIncludes:           boxIncludes,
		Gallery:               []byte(input.Gallery),
		CategoryImage:         pgtype.Text{String: input.CategoryImage, Valid: true},
		RecommendedProductIds: idsToInt64s(input.RecommendedProductIds),
	})
	if err != nil {
		return nil, fmt.Errorf("create product: %w", err)
	}

	return productToModel(product), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID %q: %w", id, err)
	}

	product, err := r.Queries.UpdateProduct(ctx, repo.UpdateProductParams{
		ID:                    productID,
		Name:                  input.Name,
		PriceInCents:          input.PriceInCents,
		Slug:                  pgtype.Text{String: input.Slug, Valid: true},
		ShortName:             pgtype.Text{String: input.ShortName, Valid: true},
		CategoryID:            pgtype.Int8{Int64: int64(input.CategoryID), Valid: true},
		IsNew:                 input.IsNew,
		Description:           pgtype.Text{String: input.Description, Valid: true},
		Features:              pgtype.Text{String: input.Features, Valid: true},
		BoxIncludes:           []byte(input.BoxIncludes),
		Gallery:               []byte(input.Gallery),
		CategoryImage:         pgtype.Text{String: input.CategoryImage, Valid: true},
		RecommendedProductIds: idsToInt64s(input.RecommendedProductIds),
	})

	if err != nil {
		return nil, fmt.Errorf("update product %d: %w", productID, err)
	}

	return productToModel(product), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID %q: %w", id, err)
	}

	product, err := r.Queries.DeleteProduct(ctx, productID)
	if err != nil {
		return nil, fmt.Errorf("delete product %d: %w", productID, err)
	}

	return productToModel(product), nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user, err := r.Accounts.CreateAccount(ctx, auth.AccountInput{
		Name:        input.Name,
		Email:       input.Email,
		Password:    input.Password,
		PhoneNumber: input.PhoneNumber,
		Country:     input.Country,
		Username:    input.Username,
	})
	if err != nil {
		return nil, err
	}

	return userToModel(user), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.Queries.ListProducts(ctx)
	if err != nil {
		return nil, fmt.Errorf("list products: %w", err)
	}

	result := make([]*model.Product, len(products))
	for i, product := range products {
		result[i] = productToModel(product)
	}

	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID %q: %w", id, err)
	}

	product, err := r.Queries.GetProductByID(ctx, productID)
	if err != nil {
		return nil, fmt.Errorf("get product %d: %w", productID, err)
	}

	return productToModel(product), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
