scalar Time
scalar DateTime
scalar JSON

enum UserRole {
  ADMIN
  CUSTOMER
}

type Product {
  id: ID!
  name: String!
  priceInCents: Int!
  createdAt: DateTime          # nullable in DB (pgtype.Timestamp)
  slug: String
  shortName: String
  categoryId: ID
  isNew: Boolean!
  description: String
  features: String
  boxIncludes: JSON!
  gallery: JSON!
  categoryImage: String
  recommendedProductIds: [ID!]!
}

input BoxItemInput {
  quantity: Int!,
  item: String!
}

input CreateProductInput {
  name: String!
  priceInCents: Int!
  slug: String!
  shortName: String!
  categoryId: Int!
  isNew: Boolean!
  description: String!
  features: String!
  boxIncludes: [BoxItemInput!]!
  gallery: JSON!
  categoryImage: String!
  recommendedProductIds: [Int!]!
}

input UpdateProductInput {
  name: String!
  priceInCents: Int!
  slug: String!
  shortName: String!
  categoryId: Int!
  isNew: Boolean!
  description: String!
  features: String!
  boxIncludes: JSON!
  gallery: JSON!
  categoryImage: String!
  recommendedProductIds: [Int!]!
}

# users schema
type User {
  id: ID!
  name: String!
  email: String!
  phoneNumber: String!
  country: String!
  username: String!
  role: UserRole!
  emailVerified: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
}

input CreateUserInput {
  name: String!
  email: String!
  phoneNumber: String!
  country: String!
  username: String!
  password: String!
}

type Query {
  products: [Product!]!
  product(id: ID!): Product
  users(limit: Int = 20, offset: Int = 0): [User!]!
}

type Mutation {
  createProduct(input: CreateProductInput!): Product!
  updateProduct(id: ID!, input: UpdateProductInput!): Product!
  deleteProduct(id: ID!): Product!

  createAccount(input: CreateUserInput!): User!
}