package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"github/M-b-a-s/e-comm/graph/model"
	repo "github/M-b-a-s/e-comm/internal/adapters/postgresql/sqlc"
	"strconv"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	product, err := r.Queries.CreateProduct(ctx, repo.CreateProductParams{
		Name:                  input.Name,
		PriceInCents:          input.PriceInCents,
		Slug:                  pgtype.Text{String: input.Slug, Valid: true},
		ShortName:             pgtype.Text{String: input.ShortName, Valid: true},
		CategoryID:            pgtype.Int8{Int64: int64(input.CategoryID), Valid: true},
		IsNew:                 input.IsNew,
		Description:           pgtype.Text{String: input.Description, Valid: true},
		Features:              pgtype.Text{String: input.Features, Valid: true},
		BoxIncludes:           []byte(input.BoxIncludes),
		Gallery:               []byte(input.Gallery),
		CategoryImage:         pgtype.Text{String: input.CategoryImage, Valid: true},
		RecommendedProductIds: int32sToInt64s(input.RecommendedProductIds),
	})
	if err != nil {
		return nil, fmt.Errorf("create product: %w", err)
	}

	return productToModel(product), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	// Parse the product ID from string to int64
	productID, err := strconv.ParseInt(id, 10, 64)

	// Handle the error if the ID is not a valid integer
	if err != nil {
		return nil, fmt.Errorf("invalid product ID %q: %w", id, err)
	}

	// Call the UpdateProduct method from the Queries interface with the parsed ID and input parameters
	product, err := r.Queries.UpdateProduct(ctx, repo.UpdateProductParams{
		ID:                    productID,
		Name:                  input.Name,
		PriceInCents:          input.PriceInCents,
		Slug:                  pgtype.Text{String: input.Slug, Valid: true},
		ShortName:             pgtype.Text{String: input.ShortName, Valid: true},
		CategoryID:            pgtype.Int8{Int64: int64(input.CategoryID), Valid: true},
		IsNew:                 input.IsNew,
		Description:           pgtype.Text{String: input.Description, Valid: true},
		Features:              pgtype.Text{String: input.Features, Valid: true},
		BoxIncludes:           []byte(input.BoxIncludes),
		Gallery:               []byte(input.Gallery),
		CategoryImage:         pgtype.Text{String: input.CategoryImage, Valid: true},
		RecommendedProductIds: int32sToInt64s(input.RecommendedProductIds),
	})

	// Handle the error if the update operation fails
	if err != nil {
		return nil, fmt.Errorf("update product %d: %w", productID, err)
	}

	// Return the updated product converted to the GraphQL model format
	return productToModel(product), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID %q: %w", id, err)
	}

	product, err := r.Queries.DeleteProduct(ctx, productID)
	if err != nil {
		return nil, fmt.Errorf("delete product %d: %w", productID, err)
	}

	return productToModel(product), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.Queries.ListProducts(ctx)
	if err != nil {
		return nil, fmt.Errorf("list products: %w", err)
	}

	result := make([]*model.Product, len(products))
	for i, product := range products {
		result[i] = productToModel(product)
	}

	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID %q: %w", id, err)
	}

	product, err := r.Queries.GetProductByID(ctx, productID)
	if err != nil {
		return nil, fmt.Errorf("get product %d: %w", productID, err)
	}

	return productToModel(product), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func productToModel(product repo.Product) *model.Product {
	return &model.Product{
		ID:                    strconv.FormatInt(product.ID, 10),
		Name:                  product.Name,
		PriceInCents:          product.PriceInCents,
		CreatedAt:             product.CreatedAt.Time,
		Slug:                  product.Slug.String,
		ShortName:             product.ShortName.String,
		CategoryID:            int32(product.CategoryID.Int64),
		IsNew:                 product.IsNew,
		Description:           product.Description.String,
		Features:              product.Features.String,
		BoxIncludes:           string(product.BoxIncludes),
		Gallery:               string(product.Gallery),
		CategoryImage:         product.CategoryImage.String,
		RecommendedProductIds: int64sToInt32s(product.RecommendedProductIds),
	}
}

func int32sToInt64s(values []int32) []int64 {
	result := make([]int64, len(values))
	for i, value := range values {
		result[i] = int64(value)
	}
	return result
}

func int64sToInt32s(values []int64) []int32 {
	result := make([]int32, len(values))
	for i, value := range values {
		result[i] = int32(value)
	}
	return result
}
