scalar Time

type Product {
  id: ID!
  name: String!
  priceInCents: Int!
  slug: String!
  shortName: String!
  categoryId: Int!
  isNew: Boolean!
  description: String!
  features: String!
  boxIncludes: String!
  gallery: String!
  categoryImage: String!
  recommendedProductIds: [Int!]!
  createdAt: Time!
}

input BoxItemInput {
  quantity: Int!,
  item: String!
}

input CreateProductInput {
  name: String!
  priceInCents: Int!
  slug: String!
  shortName: String!
  categoryId: Int!
  isNew: Boolean!
  description: String!
  features: String!
  boxIncludes: [BoxItemInput!]!
  gallery: [String!]!
  categoryImage: String!
  recommendedProductIds: [Int!]!
}

input UpdateProductInput {
  name: String!
  priceInCents: Int!
  slug: String!
  shortName: String!
  categoryId: Int!
  isNew: Boolean!
  description: String!
  features: String!
  boxIncludes: String!
  gallery: String!
  categoryImage: String!
  recommendedProductIds: [Int!]!
}

type Query {
  products: [Product!]!
  product(id: ID!): Product
}

type Mutation {
  createProduct(input: CreateProductInput!): Product!
  updateProduct(id: ID!, input: UpdateProductInput!): Product!
  deleteProduct(id: ID!): Product!
}