// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateProductInput struct {
	Name         string `json:"name"`
	PriceInCents int32  `json:"priceInCents"`
	Quantity     int32  `json:"quantity"`
}

type Mutation struct {
}

type Product struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	PriceInCents int32     `json:"priceInCents"`
	Quantity     int32     `json:"quantity"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Query struct {
}

type UpdateProductInput struct {
	Name         string `json:"name"`
	PriceInCents int32  `json:"priceInCents"`
	Quantity     int32  `json:"quantity"`
}
